language: "zh"

pipeline:
- name: HFTransformersNLP
  # Name of the language model to use
  model_name: "bert"
  # Pre-Trained weights to be loaded
  model_weights: "bert-base-chinese"
  # An optional path to a specific directory to download and cache the pre-trained model weights.
  # The `default` cache_dir is the same as https://huggingface.co/transformers/serialization.html#cache-directory .
  cache_dir: null
- name: "LanguageModelTokenizer"
- name: "LanguageModelFeaturizer"
- name: "EntitySynonymMapper"
- name: "CRFEntityExtractor"
- name: "SklearnIntentClassifier"


policies:
  - name: TEDPolicy
    epochs: 200
    max_history: 10
  - name: FallbackPolicy
    fallback_action_name: 'action_default_fallback'
  - name: MemoizationPolicy
    max_history: 10
  - name: FormPolicy
  - name: MappingPolicy